### ISSUE TITLE
Vue3.0 support

### ISSUE THREAD

**Issue by jahnli** [DataV-Team/DataV#146]
Could you tell me the author , Do you plan to support Vue3.0 and when do you expect to implement it

**Comment by jiaming743** [comment]
Of course！

Coming soon

**Comment by jahnli** [comment]
六六六

**Comment by sonicsunsky** [comment]
vue3.0会报错

**Comment by sonicsunsky** [comment]
vue3.0会报错：VueCompilerError: <template v-for> key should be placed on the <template> tag.

**Comment by sonicsunsky** [comment]
error  in ./node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue?vue&type=template&id=00bc6d25&bindings={"color":"props","ref":"data","svgWH":"data","svgScale":"data","rowNum":"data","rowPoints":"data","rectWidth":"data","halfRectWidth":"data","points":"data","heights":"data","minHeights":"data","randoms":"data","defaultColor":"data","mergedColor":"data","afterAutoResizeMixinInit":"options","calcSVGData":"options","calcPointsPosition":"options","calcScale":"options","onResize":"options","mergeColor":"options"}

Module Error (from ./node_modules/vue-loader-v16/dist/templateLoader.js):

VueCompilerError: <template v-for> key should be placed on the <template> tag.
at /Users/zhongkesun/Projects/bigdata-v3-cli/node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue:8:11
6  |        >
7  |          <rect
8  |            :key="i"
   |            ^^^^^^^^
9  |            :fill="mergedColor[Math.random() > 0.5 ? 0 : 1]"
10 |            :x="point[0] - halfRectWidth"


 @ ./node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue?vue&type=template&id=00bc6d25&bindings={"color":"props","ref":"data","svgWH":"data","svgScale":"data","rowNum":"data","rowPoints":"data","rectWidth":"data","halfRectWidth":"data","points":"data","heights":"data","minHeights":"data","randoms":"data","defaultColor":"data","mergedColor":"data","afterAutoResizeMixinInit":"options","calcSVGData":"options","calcPointsPosition":"options","calcScale":"options","onResize":"options","mergeColor":"options"} 1:0-831 1:0-831
 @ ./node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue
 @ ./node_modules/@jiaminghi/data-view/lib/components/decoration6/index.js
 @ ./node_modules/@jiaminghi/data-view/lib/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.20:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by hlbj105** [comment]
> error in ./node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue?vue&type=template&id=00bc6d25&bindings={"color":"props","ref":"data","svgWH":"data","svgScale":"data","rowNum":"data","rowPoints":"data","rectWidth":"data","halfRectWidth":"data","points":"data","heights":"data","minHeights":"data","randoms":"data","defaultColor":"data","mergedColor":"data","afterAutoResizeMixinInit":"options","calcSVGData":"options","calcPointsPosition":"options","calcScale":"options","onResize":"options","mergeColor":"options"}
> 
> Module Error (from ./node_modules/vue-loader-v16/dist/templateLoader.js):
> 
> VueCompilerError: key should be placed on the tag.
> at /Users/zhongkesun/Projects/bigdata-v3-cli/node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue:8:11
> 6 | >
> 7 | <rect
> 8 | :key="i"
> | ^^^^^^^^
> 9 | :fill="mergedColor[Math.random() > 0.5 ? 0 : 1]"
> 10 | :x="point[0] - halfRectWidth"
> 
> @ ./node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue?vue&type=template&id=00bc6d25&bindings={"color":"props","ref":"data","svgWH":"data","svgScale":"data","rowNum":"data","rowPoints":"data","rectWidth":"data","halfRectWidth":"data","points":"data","heights":"data","minHeights":"data","randoms":"data","defaultColor":"data","mergedColor":"data","afterAutoResizeMixinInit":"options","calcSVGData":"options","calcPointsPosition":"options","calcScale":"options","onResize":"options","mergeColor":"options"} 1:0-831 1:0-831
> @ ./node_modules/@jiaminghi/data-view/lib/components/decoration6/src/main.vue
> @ ./node_modules/@jiaminghi/data-view/lib/components/decoration6/index.js
> @ ./node_modules/@jiaminghi/data-view/lib/index.js
> @ ./src/main.js
> @ multi (webpack)-dev-server/client?http://192.168.1.20:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

我每次都手动去改依赖包文件，把key放在temple上
