### ISSUE TITLE
请问DataV什么时候能支持element-plus版本？

### ISSUE THREAD

**Issue by ythlibo** [DataV-Team/DataV#221]
ERROR  Failed to compile with 2 errors                                                                 9:07:55

 error  in ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration3/src/main.vue?vue&type=template&id=3f3cea2d

Module Error (from ./node_modules/_vue-loader-v16@16.0.0-beta.5.4@vue-loader-v16/dist/templateLoader.js):

VueCompilerError: <template v-for> key should be placed on the <template> tag.
at /Users/libo/work/code/yth/wcp-front-vue3/node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration3/src/main.vue:9:11
7  |        >
8  |          <rect
9  |            :key="i"
   |            ^^^^^^^^
10 |            :fill="mergedColor[0]"
11 |            :x="point[0] - halfPointSideLength"

 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration3/src/main.vue?vue&type=template&id=3f3cea2d 1:0-454 1:0-454
 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration3/src/main.vue
 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration3/index.js
 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.11.2@webpack-dev-server/client?http://192.168.1.4:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js babel-polyfill classlist-polyfill

 error  in ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration6/src/main.vue?vue&type=template&id=365371ec

Module Error (from ./node_modules/_vue-loader-v16@16.0.0-beta.5.4@vue-loader-v16/dist/templateLoader.js):

VueCompilerError: <template v-for> key should be placed on the <template> tag.
at /Users/libo/work/code/yth/wcp-front-vue3/node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration6/src/main.vue:8:11
**

```
**### > 6  |        >
> 7  |          <rect
> 8  |            :key="i"
>    |            ^^^^^^^^
> 9  |            :fill="mergedColor[Math.random() > 0.5 ? 0 : 1]"
> 10 |            :x="point[0] - halfRectWidth"**
```

**

 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration6/src/main.vue?vue&type=template&id=365371ec 1:0-454 1:0-454
 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration6/src/main.vue
 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/components/decoration6/index.js
 @ ./node_modules/_@jiaminghi_data-view@2.10.0@@jiaminghi/data-view/lib/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@3.11.2@webpack-dev-server/client?http://192.168.1.4:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js babel-polyfill classlist-polyfill

**Comment by xcwen** [comment]
yes !!
