### ISSUE TITLE
打包时报错了。

### ISSUE THREAD

**Issue by stevenrong** [DataV-Team/DataV#23]
#### 出现Bug的组件？
npm run build
打包时报的错误
#### 控制台错误输出？

Microsoft Windows [版本 10.0.17134.472]
(c) 2018 Microsoft Corporation。保留所有权利。

d:\VProjects\DataV>npm run build

> @jiaminghi/data-view@2.4.7 build d:\VProjects\DataV
> node build/index.js

Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: "callback" argument must be a function
    at makeStatsCallback (fs.js:148:11)
    at Object.fs.stat (fs.js:924:14)
    at resolve (d:\VProjects\DataV\node_modules\@jiaminghi\fs\src\index.js:38:8)
    at new Promise (<anonymous>)
    at stat (d:\VProjects\DataV\node_modules\@jiaminghi\fs\src\index.js:37:10)
    at emptyDir (d:\VProjects\DataV\node_modules\@jiaminghi\fs\src\index.js:159:25)
    at <anonymous> } reason: TypeError: "callback" argument must be a function
    at makeStatsCallback (fs.js:148:11)
    at Object.fs.stat (fs.js:924:14)
    at resolve (d:\VProjects\DataV\node_modules\@jiaminghi\fs\src\index.js:38:8)
    at new Promise (<anonymous>)
    at stat (d:\VProjects\DataV\node_modules\@jiaminghi\fs\src\index.js:37:10)
    at emptyDir (d:\VProjects\DataV\node_modules\@jiaminghi\fs\src\index.js:159:25)
    at <anonymous>
#### 期望情况？
完成打包
#### 其他相关信息
d:\VProjects\DataV>node -v
v8.11.3
- DataV版本
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
DataV库是组件库源码库，**build**命令用于发布版本前`构建UMD版及ES6转码`等操作，需要安装一些其他的依赖如`@jiaminghi/fs`

**Comment by stevenrong** [comment]
这个报错就是从　@jiaminghi/fs　出来的，我是按上图这样改了一下，就可以build了，不清楚是不是 node&nbsp;版本不同对 Function&nbsp;的类型判断不一样了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JM"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月7日(星期四) 上午10:31
收件人:&nbsp;"DataV-Team/DataV"<DataV@noreply.github.com&gt;;
抄送:&nbsp;"容献平"<steven_rong@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DataV-Team/DataV] 打包时报错了。 (#23)




DataV库是组件库源码库，build命令用于发布版本前构建UMD版及ES6转码等操作，需要安装一些其他的依赖如@jiaminghi/fs
