### ISSUE TITLE
使用vite报错,请求大佬的指点

### ISSUE THREAD

**Issue by hulei123000** [DataV-Team/DataV#258]
Uncaught SyntaxError: The requested module '/node_modules/@jiaminghi/c-render/lib/index.js?v=9a11b98b' does not provide an export named 'default' (at main.vue:8:8)

**Comment by xujianhui1402** [comment]
使用Vite报错，Uncaught SyntaxError: import not found: deepMerge

**Comment by xujianhui1402** [comment]
> 使用Vite报错，Uncaught SyntaxError: import not found: deepMerge

我这边错误发生在dev环境下，项目打包后显示正常。

**Comment by SuperLy1999** [comment]
> > 使用Vite报错，Uncaught SyntaxError: import not found: deepMerge
> 
> 我错误地发生在开发环境下，这个项目打包后显示正常。

解决了吗，我也遇到了这个问题

**Comment by SuperLy1999** [comment]
> > 使用Vite报错，Uncaught SyntaxError: import not found: deepMerge
> 
> 我错误地发生在开发环境下，这个项目打包后显示正常。

解决了吗，我也遇到了这个问题

**Comment by shihongxins** [comment]
> Uncaught SyntaxError: The requested module '/node_modules/@jiaminghi/c-render/lib/index.js?v=9a11b98b' does not provide an export named 'default' (at main.vue:8:8)

@hulei123000 你好，请问解决了吗？

**Comment by andrewgreat** [comment]
不支持vite2+vue3
