### ISSUE TITLE
windows 下运行打包会报错

### ISSUE THREAD

**Issue by stevenrong** [DataV-Team/DataV#28]
#### 其他相关信息
是否因为是 linx 的路径不同？请指导一下，在 windows 下想自己打包出来，要怎么调整？？？
- DataV版本
- 浏览器版本
- 其他

**Comment by jiaming743** [comment]
请把报错容贴出来

**Comment by stevenrong** [comment]
Complete less file deletion!
Finish adding css import statement!
Finish adding components export statement!
After rollupCompile
Error: Command failed: rollup -c build/rollup.terser.config.js

build/entry.js → dist/datav.min.vue.js...
  1 | (function (global, factory) {
> 2 |   typeof exports === 'object' && typeof module !== 'undefined' ? factory(require('vue'), require('D:VProjectsDataV    |                                                                                                 ^ Unterminated string constant
  3 | ode_modules
  4 | ollup-plugin-vue
  5 | untime
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
vue (imported by build\entry.js)
D:VProjectsDataV
untimeplugin-vue
ormalize.js (imported by src\components\fullScreenContainer\src\main.vue, src\components\borderBox1\src\main.vue, src\components\loading\src\main.vue, src\components\borderBox5\src\main.vue, src\components\borderBox2\src\main.vue, src\components\borderBox3\src\main.vue, src\components\borderBox4\src\main.vue, src\components\borderBox7\src\main.vue, src\components\borderBox8\src\main.vue, src\components\borderBox9\src\main.vue, src\components\borderBox6\src\main.vue, src\components\borderBox10\src\main.vue, src\components\decoration3\src\main.vue, src\components\decoration1\src\main.vue, src\components\decoration2\src\main.vue, src\components\decoration4\src\main.vue, src\components\decoration8\src\main.vue, src\components\decoration5\src\main.vue, src\components\decoration6\src\main.vue, src\components\decoration9\src\main.vue, src\components\decoration7\src\main.vue, src\components\decoration10\src\main.vue, src\components\charts\src\main.vue, src\components\waterLevelPond\src\main.vue, src\components\percentPond\src\main.vue, src\components\scrollRankingBoard\src\main.vue, src\components\scrollBoard\src\main.vue, src\components\flylineChart\src\main.vue, src\components\capsuleChart\src\main.vue, src\components\conicalColumnChart\src\main.vue, src\components\activeRingChart\src\main.vue, src\components\digitalFlop\src\main.vue)
D:VProjectsDataV
untimrowser.js (imported by src\components\fullScreenContainer\src\main.vue, src\components\borderBox1\src\main.vue, src\components\loading\src\main.vue, src\components\borderBox5\src\main.vue, src\components\borderBox2\src\main.vue, src\components\borderBox3\src\main.vue, src\components\borderBox4\src\main.vue, src\components\borderBox7\src\main.vue, src\components\borderBox8\src\main.vue, src\components\borderBox9\src\main.vue, src\components\borderBox6\src\main.vue, src\components\borderBox10\src\main.vue, src\components\decoration3\src\main.vue, src\components\decoration1\src\main.vue, src\components\decoration2\src\main.vue, src\components\decoration4\src\main.vue, src\components\decoration8\src\main.vue, src\components\decoration5\src\main.vue, src\components\decoration6\src\main.vue, src\components\decoration9\src\main.vue, src\components\decoration7\src\main.vue, src\components\decoration10\src\main.vue, src\components\charts\src\main.vue, src\components\waterLevelPond\src\main.vue, src\components\percentPond\src\main.vue, src\components\scrollRankingBoard\src\main.vue, src\components\scrollBoard\src\main.vue, src\components\flylineChart\src\main.vue, src\components\capsuleChart\src\main.vue, src\components\conicalColumnChart\src\main.vue, src\components\activeRingChart\src\main.vue, src\components\digitalFlop\src\main.vue)
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
vue (guessing 'Vue')
D:VProjectsDataV
untimeplugin-vue
ormalize.js (guessing '__vue_normalize__')
D:VProjectsDataV
untimrowser.js (guessing '__vue_create_injector__')
[!] (plugin terser) SyntaxError: Unterminated string constant
SyntaxError: Unterminated string constant
    at J (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:18883)
    at m (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:20198)
    at D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:22578
    at D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:24986
    at Object.Q [as input] (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:25325)
    at a (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:27351)
    at s (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:27405)
    at Ee (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:46621)
    at G (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:41838)
    at Se (D:\VProjects\DataV\node_modules\terser\dist\bundle.min.js:1:47429)


    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,

**Comment by stevenrong** [comment]
我的项目路径应该是 "D:VProjects\DataV"  但在这个命令行里看到的是　D:VProjectsDataV

**Comment by stevenrong** [comment]
报错信息里　require('D:VProjectsDataV | ^ Unterminated string constant　　是怎么出来的？　我的项目路径应该是　　D:VProjects\DataV   不是 D:VProjectsDataV

**Comment by jiaming743** [comment]
请全局安装rollup，安装后再次尝试 `npm i rollup -g`
这是给组件库打包的命令，用于发布版本前进行样式转换和代码压缩，对于用户来说意义不大

**Comment by stevenrong** [comment]
我把入口　index.js 的相对路径改成全路径就可以成功打包了，但是还是不知道为什么会这样的。

**Comment by jiaming743** [comment]
这个倒是有点奇怪了，node和npm版本是多少

**Comment by stevenrong** [comment]
d:\VProjects\DataV>npm -v
6.13.0

d:\VProjects\DataV>node -v
v12.13.0

**Comment by zxqzy** [comment]
我也遇到这个问题了，解决了吗现在
